{
 "title": "Cisco SG300-28PP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": {
     "query": "buckets()\r\n  |> filter(fn: (r) => r.name !~ /^_/)  // Exclude system buckets\r\n  |> keep(columns: [\"name\"])"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_percent\")\r\n  |> group(columns: [\"hostname\"])\r\n  |> distinct(column: \"hostname\")\r\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "interface_prefix",
    "query": {
     "query": "import \"regexp\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oper_status\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^[a-z]+\\d+$/)\r\n  |> filter(fn: (r) => r[\"interface\"] !~ /^loopback/)\r\n  |> filter(fn: (r) => r[\"interface\"] !~ /^tunnel/)\r\n  |> keep(columns: [\"interface\"])\r\n  |> distinct(column: \"interface\")\r\n  |> map(fn: (r) => ({\r\n      interface: regexp.replaceAllString(r: /\\d+$/, v: r.interface, t: \"\")\r\n    }))\r\n  |> distinct(column: \"interface\")"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "import \"regexp\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oper_status\")\r\n  |> filter(fn: (r) => r[\"interface\"] =~ /^${interface_prefix}\\d+$/)\r\n  |> keep(columns: [\"interface\"])\r\n  |> distinct(column: \"interface\")\r\n  |> map(fn: (r) => ({\r\n      interface: regexp.replaceAllString(r: /^${interface_prefix}/, v: r.interface, t: \"\")\r\n    }))\r\n  |> sort(columns: [\"interface\"])"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: 1 }))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"serial_number\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"serial_number\")"
    }
   ]
  },
  {
   "title": "Managment Interface IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_ip_table\")\r\n  |> filter(fn: (r) => r._field == \"ip_address\")\r\n  |> filter(fn: (r) => r._value != \"127.0.0.1\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "System Description",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"description\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"description\")"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"uptime\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 100.0 }))\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"uptime\")"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"model\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"model\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage_percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "PoE Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"pse_temperature_celsius\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"pse_temperature_celsius\")"
    }
   ]
  },
  {
   "title": "System Location",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"location\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"location\")"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"firmware_version\")\r\n  |> last()\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> yield(name: \"firmware_version\")"
    }
   ]
  },
  { "title": "Power over Ethernet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "PoE Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_poe_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"power_consumed_watts\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "PoE Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_poe_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field =~ /power_consumed_watts|power_available_watts/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "PoE Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "consumed = from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_poe_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"power_consumed_watts\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\navailable = from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_poe_system\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"power_available_watts\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\njoin(tables: {consumed: consumed, available: available}, on: [\"_time\", \"hostname\"])\r\n  |> map(fn: (r) => ({ r with _value: (r._value_consumed / r._value_available) * 100.0 }))\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "gbe${interfaces}",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "repeat": "interfaces",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oper_status\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"${interface_prefix}${interfaces}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_interface_hc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"rx_bytes\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"download\")\r\n"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"snmp_interface_hc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r._field == \"tx_bytes\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"download\")\r\n"
    }
   ]
  },
  {
   "title": "${interface_prefix}${interfaces}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "interfaces"
  },
  {
   "title": "gbe${interfaces}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"oper_status\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"${interface_prefix}${interfaces}\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "${interface_prefix}${interfaces} Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface_hc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"gi${interfaces}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface_hc\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"gi${interfaces}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_bytes\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 * -1.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"${interface_prefix}${interfaces}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_errors\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"${interface_prefix}${interfaces}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_errors\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 * -1.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "gbe${interfaces} Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp_interface\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed_bps\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"${interface_prefix}${interfaces}\")\r\n  |> last()"
    }
   ]
  }
 ]
}